### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Nousemusic** [AlexGustafsson/homebridge-wol#1]
Seems like an interesting Plugin for homebridge.

How do I install homebridge-wol?

**Comment by AlexGustafsson** [comment]
I made this for my self as a test for homebridge, but if it's useful to others I'll be sure to complement the documentation. I'll get right back to you when I'm done.

**Comment by Nousemusic** [comment]
That would be perfect. Thank you in advance.

**Comment by AlexGustafsson** [comment]
I'm having a hard time getting WoL to work on my machines (hardware/software wise, not related to this package) so I cannot currently debug the package. But feel free to look in the source if there's anything you want to know - it should be self explanatory.

To install you run ```npm install -g homebridge-wol```. After that, edit your config.json (usually in ```/root/.homebridge/config.json``` to fit your needs. You should see a key called "accessories" and that's where you can add your computer like shown in the README.md

**Comment by Nousemusic** [comment]
Perfect, thanks a lot. 

I'll try the install in the next days.

**Comment by Nousemusic** [comment]
Works perfect for me. Thank you very much.

I have the following lines added in my config:
		{
          	"accessory": "Computer",
          	"name": "PC",
          	"mac": "XX:XX:XX:XX:XX:XX"
        	}

**Comment by AlexGustafsson** [comment]
That's great to hear!
