### ISSUE TITLE
My bios don't support WOL, I'm looking for a command to "sleep" my computer

### ISSUE THREAD

**Issue by pyonjohn** [AlexGustafsson/homebridge-wol#106]
### Backstory / Issue
My bios don't support WOL so I can't wake it up with a magic packet that's why I'm looking for a command to "sleep" my computer instaed of shutting it down. I tried a lot of things with pstools, "rundll32.exe powrprof.dll,SetSuspendState 0,1,0", create a shortcut that point to "rundll32.exe powrprof.dll,SetSuspendState 0,1,0" and call it etc... but everything fail, net rpc just won't let me. Is there a workaround for putting my PC into sleep mode instead ? The WOL works well when my computer is in sleep mode but not hibernate by the way.

### Environment
* Windows : 10 (2004) 19041.329 
* node : 12.18.2
* Homebridge : 4.23.2
* homebridge-wol version : 4.2.1

### Configuration

> "accessories": [
>         {
>             "name": "<puchiInspiron-Eth>",
>             "ip": "192.168.0.20",
>             "pingInterval": 2,
>             "pingsToChange": 5,
>             "pingTimeout": 1,
>             "mac": "<mac-address>,
>             "broadcastAddress": "192.168.0.255",
>             "wakeGraceTime": 45,
>             "shutdownCommand": "net rpc shutdown --ipaddress 192.168.0.20 --user <myspecificusername>%<passwd>",
>             "shutdownGraceTime": 15,
>             "log": true,
>             "logPinger": true,
>             "debugLog": false,
>             "returnEarly": true,
>             "accessory": "NetworkDevice"
>         }
>     ]

### Log
When I follow these steps:
1. Run `DEBUG=* homebridge`
2. Let it run for five minutes
3. Tap a switch
4. Wait one minute
5. Tap the same switch

I get the following log:

> [2020-7-13 15:12:28] [puchiInspiron-Eth] NetworkDevice shutdown cycle started for "puchiInspiron-Eth" (192.168.0.20)
> [2020-7-13 15:12:28] [puchiInspiron-Eth] NetworkDevice "puchiInspiron-Eth" (192.168.0.20) went from status "Online" to "Shutting Down"
> [2020-7-13 15:12:28] [puchiInspiron-Eth] Attempting to shut down "puchiInspiron-Eth" (192.168.0.20) using "net"
> [2020-7-13 15:12:29] [puchiInspiron-Eth] An error occured while trying to shut down "puchiInspiron-Eth" (192.168.0.20): Error: Command failed: net rpc psshutdown -d -t 0  --ipaddress 192.168.0.20 --user shutdown%HelloBridge
> debug_parse_params: unrecognized debug class name or format [-t]
> mkdir failed on directory /var/run/samba/msg.lock: Permission non accordée
> Invalid command: net rpc psshutdown
> 
>     at ChildProcess.exithandler (child_process.js:303:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
>   killed: false,
>   code: 255,
>   signal: null,
>   cmd: 'net rpc psshutdown -d -t 0  --ipaddress 192.168.0.20 --user shutdown%HelloBridge',
>   stdout: 'Usage:\n' +
>     'net rpc audit           Modify global audit settings\n' +
>     'net rpc info            Show basic info about a domain\n' +
>     'net rpc join            Join a domain\n' +
>     'net rpc oldjoin         Join a domain created in server manager\n' +
>     'net rpc testjoin        Test that a join is valid\n' +
>     'net rpc user            List/modify users\n' +
>     'net rpc password        Change a user password\n' +
>     'net rpc group           List/modify groups\n' +
>     'net rpc share           List/modify shares\n' +
>     'net rpc file            List open files\n' +
>     'net rpc printer         List/modify printers\n' +
>     'net rpc changetrustpw   Change trust account password\n' +
>     'net rpc trustdom        Modify domain trusts\n' +
>     'net rpc abortshutdown   Abort a remote shutdown\n' +
>     'net rpc shutdown        Shutdown a remote server\n' +
>     "net rpc vampire         Sync a remote NT PDC's data into local passdb\n" +
>     'net rpc getsid          Fetch the domain sid into local secrets.tdb\n' +
>     'net rpc rights          Manage privileges assigned to SID\n' +
>     'net rpc service         Start/stop/query remote services\n' +
>     'net rpc registry        Manage registry hives\n' +
>     'net rpc shell           Open interactive shell on remote server\n' +
>     'net rpc trust           Manage trusts\n' +
>     'net rpc conf            Configure a remote samba server\n',
>   stderr: 'debug_parse_params: unrecognized debug class name or format [-t]\n' +
>     'mkdir failed on directory /var/run/samba/msg.lock: Permission non accordée\n' +
>     'Invalid command: net rpc psshutdown\n'
> }
> [2020-7-13 15:12:29] [puchiInspiron-Eth] Waiting for shutdown grace time (15000ms) for "puchiInspiron-Eth" (192.168.0.20)
> [2020-7-13 15:12:44] [puchiInspiron-Eth] Pinger saw device online; setting to Online.
> [2020-7-13 15:12:44] [puchiInspiron-Eth] NetworkDevice "puchiInspiron-Eth" (192.168.0.20) went from status "Shutting Down" to "Online"
> 

### Notes

Of course in the above log it didn't work as I tried with psshutdown.
The default "shutdown" works.

**Comment by Salvora** [comment]
try using ssh with shutdown /h
which will hibernate

**Comment by pyonjohn** [comment]
I found a workaround, I use
`"shutdownCommand": "sshpass -p '<password>' ssh -o StrictHostKeyChecking=no <username>@<private_ip> 'rundll32.exe powrprof.dll,SetSuspendState 0,1,0'",`

But the wake command works only some time, I have the impression that I have to wait a long time before it works when the computer is in sleep.

BTW, I tested with the hibernate, but it doesn't work too

**Comment by AlexGustafsson** [comment]
@pyonjohn You could try to run homebridge and the WoL plugin in debug mode (should be mentioned in the README or issue template). If you see any logs that indicate that the wake command was unsuccessful, you will see further logs as to why that is. If there is seemingly no issue, it's likely that your PC ignores the command or that an issue arises whilst running it. Depending on how your setup works, it's also entirely possible that the command fails since the PC simply can't be woken up due to being in a deeper state of sleep (as you're likely seing with hibernate).

**Comment by pyonjohn** [comment]
@AlexGustafsson I did everything and the log show a sending of the WoL but the computer doesn't respond. Wireshark also show me that I receive the packet. Now, I am trying the startCommand "wakeonlan -i 192.168.0.20 <macAddress>" it works better but still time to time

**Comment by AlexGustafsson** [comment]
Closing as this seems to be solved (to the extent that is solvable). Feel free to reopen if it's still an issue related to this plugin.
