### ISSUE TITLE
Ping interval not used if a ping command is set, but no ip is

### ISSUE THREAD

**Issue by AlexGustafsson** [AlexGustafsson/homebridge-wol#110]
The configuration requires an `ip` to be set for pinging, even though a `pingCommand` will do just fine. The documentation and code will need to be updated to allow the `pingCommand` to act in place of `ip`.

**Comment by AlexGustafsson** [comment]
Fixed in https://github.com/AlexGustafsson/homebridge-wol/commit/a4933410acded16db81faf70a721e26f62dfb6ee.

**Comment by crzdg** [comment]
When will this be release to NPM? I saw 4.3.0 was released on August 2020, this fix is dated Nov 2020.

**Comment by AlexGustafsson** [comment]
@crzdg I've published the latest version now, see https://github.com/AlexGustafsson/homebridge-wol/releases/tag/v5.0.0-beta.2. If you haven't yet seen the beta, please refer to #124.
