### ISSUE TITLE
Another shutdown PC question

### ISSUE THREAD

**Issue by brownad** [AlexGustafsson/homebridge-wol#112]
### Backstory
I cannot run the shutdown command from the plugin directly, the logs show no errors but fail to shutdown the remote PC

### Issue
Having setup ssh keys correctly and tested from Win10 to Win10 (CMD and GitBash) the PC is able to shutdown remotely.  However whenever I use the command within the plugin it fails to turn off the PC, but does not show any obvious errors.  After a while it will show a ! on the Switch but that's it.  At which point I have to restart homebridge for the plugin to get the correct state of the remote PC again.  Starting the PC (from hibernate) works very well, from Off it works some of the time.

### Environment
* os & os version: `Windows 10` and `Windows 10`
* node version: `12.14.1`
* homebridge version: `1.1.1`
* homebridge-wol version: `4.2.2`

### Configuration
My configuration looks like this:
```
        {
			"accessory": "NetworkDevice",
			"name": "Gamer PC",
			"ip": "192.168.0.112",
			"logPinger": true,
			"debugLog": true,
			"mac": "<mac-address>",
			"pingInterval": 2,
			"pingsToChange": 5,
			"pingTimeout": 1,
			"wakeGraceTime": 45,
			"shutdownGraceTime": 60,
			"shutdownCommand": "ssh -o StrictHostKeyChecking=no user@192.168.0.112 shutdown /s"
       }
```

### Log
When I follow these steps:
1. Run `DEBUG=* homebridge`
2. Let it run for five minutes
3. Tap a switch
4. Wait one minute
5. Tap the same switch

I get the following log:
```
[7/23/2020, 14:19:17] [Gamer PC] Got state change for "Gamer PC" (192.168.0.112): 0
[7/23/2020, 14:19:17] [Gamer PC] NetworkDevice shutdown cycle started for "Gamer PC" (192.168.0.112)
[7/23/2020, 14:19:17] [Gamer PC] NetworkDevice "Gamer PC" (192.168.0.112) went from status "Online" to "Shutting Down"
[7/23/2020, 14:19:17] [Gamer PC] Stopping pinger
[7/23/2020, 14:19:17] [Gamer PC] Attempting to shut down "Gamer PC" (192.168.0.112) using "ssh"
```

The logs are not yielding much information and stops after the shutdown was requested.

### Notes
I am running homebridge from `homebridge-config-ui-x` within `hb-service` could that affect how the ssh command is treated?

**Comment by brownad** [comment]
Solved, since homebridge is running under SYSTEM account the ssh keys need to be made under that profile.  Finally some proper WOL 👍

**Comment by AlexGustafsson** [comment]
Great you were able to solve it on your own. Thanks for providing the solution to your problem - it usually helps others looking to solve the same or a similar issue in the future!
