### ISSUE TITLE
PC start problem

### ISSUE THREAD

**Issue by borewicz9** [AlexGustafsson/homebridge-wol#114]
### Backstory
In home app there's ! (exclamation mark)

### Issue
When I try to start up my PC theres ! (exclamation mark) on icon in iOS Home app (but only on my iOS 13.5 iPad - used as Home accessory center)
My PC boot up normaly using iPhone iOS 13.5

### Environment
* os & os version: iOS13.5
* node version: v12.18.3
* homebridge version: 1.1.2
* homebridge-wol version: 1.4.0

### Configuration
My configuration looks like this:
```
            "name": "Computer",
            "ip": "192.168.1.103",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommandTimeout": 0,
            "mac": "<mac-address>",
            "startCommandTimeout": 0,
            "wakeGraceTime": 25,
            "wakeCommandTimeout": 0,
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "log": true,
            "logPinger": false,
            "debugLog": false,
            "returnEarly": true,
            "accessory": "NetworkDevice"

**Comment by AlexGustafsson** [comment]
@borewicz9 did you solve the issue?

**Comment by borewicz9** [comment]
> @borewicz9 did you solve the issue?

Ye, I’ve restore iPad software, found issues in other HB plugins too.
