### ISSUE TITLE
Accessory "Not responding" so unable to wake on Lan

### ISSUE THREAD

**Issue by Simob98** [AlexGustafsson/homebridge-wol#120]
Hi,

I just configured Homebridge-wol plugin, I am able to shutdown successfully my PC too, but I am unable to wake it up.
When it is switched off, the iOS home app say "not responding" for the Network Device.
Her's my configuration:

_{
    "bridge": {
        "name": "Homebridge A50B",
        "username": "0E:EB:08:2A:A5:0B",
        "port": 51393,
        "pin": "975-02-813"
    },
    "accessories": [
        {
            "name": "PC Fisso di Simone",
            "ip": "192.168.1.210",
            "pingInterval": 45,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommand": "ping 192.168.1.210",
            "pingCommandTimeout": 0,
            "mac": "xxx",
            "broadcastAddress": "255.255.255.0",
            "startCommandTimeout": 0,
            "wakeGraceTime": 10,
            "wakeCommandTimeout": 0,
            "shutdownCommand": "SHUTDOWN /s /t 30 /m 192.168.1.210",
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "log": true,
            "logPinger": false,
            "debugLog": false,
            "returnEarly": false,
            "accessory": "NetworkDevice"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}_

Thanks for the help

**Comment by AlexGustafsson** [comment]
Could you follow the debugging steps?

These are mentioned in the issue template. They're also available here: [https://github.com/AlexGustafsson/homebridge-wol/blob/master/.github/ISSUE_TEMPLATE/issue-template.md](https://github.com/AlexGustafsson/homebridge-wol/blob/master/.github/ISSUE_TEMPLATE/issue-template.md).

**Comment by Simob98** [comment]
How can I debug if PC is switched off? I mean the service of homebridge is off, so it is not compiling the log.
It is just not sending the magic packet to Wake up the PC, even if the Network Card is on

Thanks

**Comment by AlexGustafsson** [comment]
If homebridge is turned off, there's nothing we can do. The service will have to be on for it to work. If you're able to, try to run homebridge on a Raspberry Pi or Laptop that is always turned on.

**Comment by Simob98** [comment]
Hi,

Thank you su much for response
I will try on a raspberry

**Comment by AlexGustafsson** [comment]
@Simob98 Were you able to resolve the issue?

**Comment by AlexGustafsson** [comment]
Closing this as running homebridge on another device should solve the issue. Feel free to reopen.
