### ISSUE TITLE
homebridge on raspberry pi wol not working on windows pc

### ISSUE THREAD

**Issue by jfrenzy** [AlexGustafsson/homebridge-wol#121]
Trying to figure out how to set my homebridge to turn off my win10 pc with the homebridge wol plugin. I try to put in the command: net rpc shutdown --ipaddress 10.221.**.151 --user jfren%*with my password*

as the instructions say, but when run through homekit i get a response in the log:

An error occurred while trying to shut down "Pc" (10.221.--.151): Error: Command failed: net rpc shutdown --ipaddress 10.221.--.151 --user jfren%*again my password*
/bin/sh: 1: net: not found

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'net rpc shutdown --ipaddress 10.221.--.151 --user jfren%*mypass*',
  stdout: '',
  stderr: '/bin/sh: 1: net: not found\n'

I have tried multiple commands including a simple Shutdown /s which returns no better. I would really like to get this to work so any help would be much appreciated!

**Comment by AlexGustafsson** [comment]
The command is not available, meaning it’s likely not installed. Please see this similar issue; https://github.com/AlexGustafsson/homebridge-wol/issues/102.

Depending on your system, it should be as easy as: `sudo apt-get install samba-common-bin`.

**Comment by jfrenzy** [comment]
@AlexGustafsson alright, I install the package and I'm much closer, but it still returns with an error, here's the code:

NetworkDevice shutdown cycle started for "Pc" (10.221.19.151)
[9/26/2020, 02:23:34] [Pc] NetworkDevice "Pc" (10.221.19.151) went from status "Online" to "Shutting Down"
[9/26/2020, 02:23:34] [Pc] Attempting to shut down "Pc" (10.221.19.151) using "net"
[9/26/2020, 02:23:44] [Pc] An error occured while trying to shut down "Pc" (10.221.19.151): Error: Command failed: net rpc shutdown -I 10.0.5.2 -U shutdown%
Could not connect to server 10.0.5.2
Connection failed: NT_STATUS_IO_TIMEOUT
Could not connect to server 10.0.5.2
Connection failed: NT_STATUS_IO_TIMEOUT

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 255,
  signal: null,
  cmd: 'net rpc shutdown -I 10.0.5.2 -U shutdown%',
  stdout: '',
  stderr: 'Could not connect to server 10.0.5.2\n' +
    'Connection failed: NT_STATUS_IO_TIMEOUT\n' +
    'Could not connect to server 10.0.5.2\n' +
    'Connection failed: NT_STATUS_IO_TIMEOUT\n'

**Comment by jfrenzy** [comment]
I did try a new command that I found online but I got the sam, could not connect to server error

**Comment by jfrenzy** [comment]
An error occured while trying to shut down "Pc" (10.221.19.151): Error: Command failed: net rpc shutdown --ipaddress 10.221.19.151 --user jfren%554351
Could not connect to server 10.221.19.151
The username or password was not correct.
Connection failed: NT_STATUS_LOGON_FAILURE
Could not connect to server 10.221.19.151
The username or password was not correct.
Connection failed: NT_STATUS_LOGON_FAILURE

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: 'net rpc shutdown --ipaddress 10.221.19.151 --user jfren%554351',
  stdout: '',
  stderr: 'Could not connect to server 10.221.19.151\n' +
    'The username or password was not correct.\n' +
    'Connection failed: NT_STATUS_LOGON_FAILURE\n' +
    'Could not connect to server 10.221.19.151\n' +
    'The username or password was not correct.\n' +
    'Connection failed: NT_STATUS_LOGON_FAILURE\n'

**Comment by AlexGustafsson** [comment]
The last failed command suggests that your username or password is incorrect.

**Comment by AlexGustafsson** [comment]
Closing this as the correct credentials will likely resolve the issue. Feel free to reopen if you're still having issues.

**Comment by yksoon** [comment]
I installed homebridge on my synology NAS. So I can't use apt-get and yum. How can I install samba-common-bin?
