### ISSUE TITLE
Different icons

### ISSUE THREAD

**Issue by roberkane212** [AlexGustafsson/homebridge-wol#122]
This is not really an issue at all, more of a question. Is it possible we can have more options for icons? I use this for my network and would love to be able to use the router icon than the switch. I understand coding goes into this so if not I understand

**Comment by AlexGustafsson** [comment]
No worries. Unfortunately, iconography is not up to us. They're managed by Apple (or any other program implementing the HomeKit library).

Your best bet is to use a third-party application for managing your router etc. Examples are https://github.com/oznu/homebridge-config-ui-x (natively supported by this project, web-based) and Eve for HomeKit for iOS.

**Comment by roberkane212** [comment]
@AlexGustafsson no problem. I have no need to actually manage my routers as they are already HomeKit compatible. I use this plugin to show the network of my printer. I know that the icon number of the router was 28, and know maybe people that have written the code to have multiple icons just was wondering if you weee able to. If not it’s fine no biggie I can just use the switch icon for now

**Comment by AlexGustafsson** [comment]
HomeKit itself does not support any special icons. This plugin is for HomeKit and currently there’s no plan to implement any third-party extensions. What application do you use to control your devices?

**Comment by roberkane212** [comment]
The icon I’m speaking of is not special, it is an icon within HomeKit. however I can see you will not can the capability to implement this which is fine. I have no real need for the switch of icon others than look. Just like set top box and other icons have been added directly to HomeKit itself. I’m not sure if you are confused by my question, however it’s no big issue you can close it. By application what do you mean?

**Comment by AlexGustafsson** [comment]
HomeKit exposes services, Apple’s Home app hooks them up to specific icons. Some third-party apps allow you to change the icon no matter the service an accessory exposes. So I thought you were talking about another app. I could actually look into if we could allow users to configure what service is exported. When this plugin was originally created, the switch was basically the only service which supported the On/Off states, which made it perfect for turning on or off PCs. If there are more types of accessories supported now, such as routers and speakers, one might be able to quite effortlessly make it configurable. That could in theory change the icon in the Home app. Sorry for the confusion, I’ll look into it.

**Comment by roberkane212** [comment]
@AlexGustafsson 
![A28060EF-3C5B-420A-8CEC-6F51F2590768](https://user-images.githubusercontent.com/44589993/95024255-e2ab6b00-064f-11eb-9b1e-bb8da522a5d5.jpeg)
Yes I have added these to HomeKit along with tv icons ect. Like I said before no issue, just wanted to ask

**Comment by roberkane212** [comment]
@AlexGustafsson 
![D72F0F1C-793D-4E0E-BDEA-2F8A8F3DD4DF](https://user-images.githubusercontent.com/44589993/95024373-9f9dc780-0650-11eb-98aa-5c261fb8ec92.jpeg)

**Comment by AlexGustafsson** [comment]
I'm closing this issue in favor of #123. You can follow the progress there. Don't expect it to be done anytime soon, however. Thanks for creating this issue and suggesting the cool feature!
