### ISSUE TITLE
Not working with Homebridge and a Windows PC

### ISSUE THREAD

**Issue by RelishedChicken** [AlexGustafsson/homebridge-wol#125]
### Backstory
I'm trying to get this to work on a HOOBS Raspberry Pi, the plugin installed and is attempting to ping my PC. As far as I can tell, I've set up everything to allow it to ping the device. Whenever it pings my PC though, it gets no reply and thinks it's offline?

### Issue
I feel that this could be an issue with my configuration, not 100% sure.

### Environment
* HOOBS Homebridge 3.2.9
* node version: 12.16.3
* homebridge version: Unsure but most likely the latest as this HOOB update is only 3 days old
* homebridge-wol version: Latest

### Configuration
My configuration looks like this:
```
"accessories": [
        {
            "accessory": "NetworkDevice",
            "plugin_map": {
                "plugin_name": "homebridge-wol",
                "index": 0
            },
            "name": "Veeraj's PC",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommandTimeout": 0,
            "startCommandTimeout": 0,
            "wakeGraceTime": 45,
            "wakeCommandTimeout": 0,
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "log": true,
            "logPinger": true,
            "debugLog": true,
            "returnEarly": false,
            "ip": "192.168.0.176",
            "mac": "<my-pc-mac-address>"
        }
    ],
```

### Log
When I follow these steps:
1. Make sure `logLevel` is set to `Debug` on all `NetworkDevice` accessories
2. Run `homebridge`
3. Let it run for a couple of minutes
4. Try to turn a device on or off using the plugin
5. Wait one minute
6. Repeat step 4

I get the following log:
```
26/10/2020, 10:07:38 [Veeraj's PC] Got state change from pinger for "Veeraj's PC" (192.168.0.176): offline
26/10/2020, 10:07:39 [Veeraj's PC] Attempting to ping "Veeraj's PC" (192.168.0.176)
26/10/2020, 10:07:40 [Veeraj's PC] Result of pinging "Veeraj's PC" (192.168.0.176): offline
26/10/2020, 10:07:41 [Veeraj's PC] Attempting to ping "Veeraj's PC" (192.168.0.176)
26/10/2020, 10:07:42 [Veeraj's PC] Result of pinging "Veeraj's PC" (192.168.0.176): offline
26/10/2020, 10:07:43 [Veeraj's PC] Attempting to ping "Veeraj's PC" (192.168.0.176)
26/10/2020, 10:07:44 [Veeraj's PC] Result of pinging "Veeraj's PC" (192.168.0.176): offline
26/10/2020, 10:07:45 [Veeraj's PC] Attempting to ping "Veeraj's PC" (192.168.0.176)
26/10/2020, 10:07:46 [Veeraj's PC] Result of pinging "Veeraj's PC" (192.168.0.176): offline
26/10/2020, 10:07:47 [Veeraj's PC] Attempting to ping "Veeraj's PC" (192.168.0.176)
26/10/2020, 10:07:48 [Veeraj's PC] Result of pinging "Veeraj's PC" (192.168.0.176): offline
26/10/2020, 10:07:48 [Veeraj's PC] Got 0 positives out of 5
```

**Comment by AlexGustafsson** [comment]
Are you sure you’re using the correct IP? `192.168.0.176` is quite uncommon but it should work if that’s your IP.

**Comment by RelishedChicken** [comment]
Yeah, that’s my PC’s IPv4 address, checked when running ‘ipconfig’ on cmd.

I may give it a reboot and see if it helps

**Comment by RelishedChicken** [comment]
Ah I found out why! For some reason, on Windows 10, if you don't have 'File and Printer Sharing' turned on in the advanced sharing settings in control panel, it does not accept ping requests, hence the plugin thought that my PC was offline!

I found out about that here: https://superuser.com/questions/1137912/ping-to-windows-10-not-working-if-file-and-printer-sharing-is-turned-off

**Comment by RelishedChicken** [comment]
I have a question actually, that I don't really want to raise a new ticket for. How exactly do I setup the shutdown command for the computer? I'm guessing 'net rpc' won't work with Windows 10 as it seems to be a Linux thing?

**Comment by AlexGustafsson** [comment]
Great! Thank you for sharing the solution. Feel free to try out the new version of this plugin: #124.

**Comment by AlexGustafsson** [comment]
The command is basically the same, but there's also a `shutdown` command you can use on Windows:

https://www.howtogeek.com/109655/how-to-remotely-shut-down-or-restart-windows-pcs/

**Comment by RelishedChicken** [comment]
Ah ok I see, I think its working now after some UAC changes. One final thing, for starting up the computer, can I use 'wol://<mac-address>'? I've seen a much older plugin do this and that's the only bit of that one that worked. I'm not able to turn on the PC currently otherwise.

**Comment by RelishedChicken** [comment]
Actually don't worry, I just tried putting the wol URL in and it just worked! Brilliant!

**Comment by AlexGustafsson** [comment]
@RelishedChicken Would you mind elaborating on the `wol://` URL? I haven't actually seen that used before, let alone in the context of this plugin.

**Comment by RelishedChicken** [comment]
Ah sure, basically in an older plugin (https://www.npmjs.com/package/homebridge-winpc) you could set the 'onUrl' (the url to use to turn the PC on) as a Wake on LAN URL. As far as I can tell its format is "wol://XX:XX:XX:XX:XX" where the X's are replaced with a MAC address of the computer you want to turn on. I'm not sure if it's limited to Linux but it's worked using this plugin on a Raspberry Pi.

**Comment by RelishedChicken** [comment]
Okay just have tried to start my PC this morning through HomeKit and ran into an issue. Log is as follows:

‘’’
27/10/2020, 08:45:49 [Veeraj's PC] Stopping pinger
27/10/2020, 08:45:49 [Veeraj's PC] Attempting to start "Veeraj's PC" (192.168.0.176) by sending a WoL packet
27/10/2020, 08:45:50 (node:25044) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of null
27/10/2020, 08:45:50 at NetworkDevice.wake (/home/hoobs/.hoobs/node_modules/homebridge-wol/lib/network-device.js:185:51)
27/10/2020, 08:45:50 at processTicksAndRejections (internal/process/task_queues.js:97:5)
27/10/2020, 08:45:50 at async NetworkDevice.setOnline (/home/hoobs/.hoobs/node_modules/homebridge-wol/lib/network-device.js:138:9)
27/10/2020, 08:45:50 (node:25044) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
27/10/2020, 08:45:50 (node:25044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
‘’’

**Comment by AlexGustafsson** [comment]
You've stumbled upon a typo:

```js
// ...
if (this.config.startCommand) {
    const commandName = this.config.wakeCommand.split(' ')[0]; // <-- It fails here due to startCommand being available, but it erroneously using the wakeCommand instead
    this.log('Attempting to start "%s" (%s) using "%s"', this.config.name, this.config.ip || 'unknown ip', commandName);
   try {
      await exec(this.config.startCommand, {timeout: this.config.startCommandTimeout});
    } catch (error) {
      this.log('An error occured while trying to start "%s" (%s): %s', this.config.name, this.config.ip || 'unknown ip', error);
      this.debugLog(error);
    }
   woke = true;
  }
// ...
```

It's fixed in the upcoming version:

```ts
// ...
if (this.config.startCommand) {
  const commandName = this.config.startCommand.split(" ")[0];
  this.log.info("Attempting to start the device using command \"%s\"", commandName);
  try {
    await exec(this.config.startCommand, {timeout: this.config.startCommandTimeout});
  } catch (error) {
    this.log.error("An error occured while trying to start the device");
    this.log.debug(error);
  }
  woke = true;
 }
// ...
```

 Feel free to try it out. There's instructions on how to install it here: #124. It basically boils down to `npm install --global homebridge-wol@beta`. Note that this is a so called major release, so there are breaking changes but it should take less than a minute to resolve.

**Comment by RelishedChicken** [comment]
Ah ok I see, I’ll have to give it a shot later today! I’ll let you know if it fixes this.

**Comment by RelishedChicken** [comment]
Hey, I've just realised, I'm using HOOBS, which has it's own UI and such, hence I never install through the terminal and as far as I know, HOOBS doesn't allow global installation for security (odd but their choice). Is there something I can do in my Raspberry Pi's terminal to update the current homebridge-wol plugin to the beta branch?

**Comment by AlexGustafsson** [comment]
I have no experience with HOOBS, but one should be able to execute standard npm commands to uninstall and then install the new version: https://github.com/hoobs-org/HOOBS/issues/186.

**Comment by RelishedChicken** [comment]
Hey, I just tried this and I believe I have the beta version installed now, seems to be working fine! I’ll put new issues on the beta branch if there are any!
