### ISSUE TITLE
Wol plugin not shutting down anymore, only waking up.

### ISSUE THREAD

**Issue by angelflames1337** [AlexGustafsson/homebridge-wol#135]
### Backstory
After some times using this plugin flawlessly, noticed the plugin doesn't shutdown my pc, only waking up working. 

### Issue
When in homebridge/homekit, pressing the button to shutdown pc doesnt work. Nothing changes in the configuration, except I updated the plugin recently. Running the command manually from any machine in my network work. sudo wget http://192.168.1.109:5001

Below is the error:

> 

[1/7/2021, 1:26:23 PM] [PC] Attempting to shut down "PC" (192.168.1.109) using "sudo"
[1/7/2021, 1:26:23 PM] [PC] An error occured while trying to shut down "PC" (192.168.1.109): Error: Command failed: sudo wget http://192.168.1.109:5001

### Environment
* os & os version: Alpine Linux (3.12.3)
* node version: 	v14.15.3
* homebridge version: homebridge-config-ui-x v4.36.0 
* homebridge-wol version: homebridge-wol v4.3.0 

### Configuration
My configuration looks like this:

    "accessories": [
        {
            "name": "PC",
            "ip": "192.168.1.109",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommandTimeout": 0,
            "mac": "<mac-address>",
            "startCommandTimeout": 0,
            "wakeGraceTime": 45,
            "wakeCommandTimeout": 0,
            "shutdownCommand": "sudo wget http://192.168.1.109:5001",
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "log": true,
            "logPinger": false,
            "debugLog": false,
            "returnEarly": true,
            "accessory": "NetworkDevice"
        },

Please paste your homebridge config.json here

 

> {
>     "bridge": {
>         "name": "Homebridge 47D3",
>         "username": "<mac-address>",
>         "port": 52104,
>         "pin": "040-11-804"
>     },
>     "description": "This file is used for plugin configuration.",
>     "accessories": [
>         {
>             "name": "PC",
>             "ip": "192.168.1.109",
>             "pingInterval": 3,
>             "pingsToChange": 3,
>             "pingTimeout": 1,
>             "pingCommandTimeout": 0,
>             "mac": "<mac-address>",
>             "startCommandTimeout": 0,
>             "wakeGraceTime": 45,
>             "wakeCommandTimeout": 0,
>             "shutdownCommand": "sudo wget http://192.168.1.109:5001",
>             "shutdownGraceTime": 15,
>             "shutdownCommandTimeout": 0,
>             "log": true,
>             "logPinger": true,
>             "debugLog": true,
>             "returnEarly": true,
>             "accessory": "NetworkDevice"
>         },
>         {
>             "accessory": "SonoffTasmotaHTTP",
>             "name": "Counter Bulb",
>             "hostname": "192.168.1.80"
>         },
>         {
>             "accessory": "SonoffTasmotaHTTP",
>             "name": "Downlight",
>             "hostname": "192.168.1.81"
>         },
>         {
>             "accessory": "SonoffTasmotaHTTP",
>             "name": "Hall Light",
>             "relay": "1",
>             "hostname": "192.168.1.82"
>         },
>         {
>             "accessory": "SonoffTasmotaHTTP",
>             "name": "Hall Fan",
>             "relay": "2",
>             "hostname": "192.168.1.82"
>         }
>     ],
>     "platforms": [
>         {
>             "name": "Config",
>             "port": 8080,
>             "auth": "none",
>             "theme": "dark-mode",
>             "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
>             "tempUnits": "c",
>             "lang": "auto",
>             "sudo": true,
>             "standalone": true,
>             "log": {
>                 "method": "custom",
>                 "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
>             },
>             "platform": "config"
>         },
>         {
>             "platform": "BraviaOSPlatform",
>             "name": "BraviaTVOS",
>             "tvs": [
>                 {
>                     "name": "Sony Bravia TV",
>                     "ip": "192.168.1.74",
>                     "port": 80,
>                     "timeout": 5,
>                     "psk": "04011804",
>                     "apps": [
>                         "Kodi",
>                         "YouTube",
>                         "Netflix"
>                     ],
>                     "channels": [
>                         "[3@tv:dvbt] TV3 HD"
>                     ],
>                     "speaker": {
>                         "increaseBy": 1,
>                         "reduceBy": 1
>                     }
>                 }
>             ]
>         }
>     ]
> }

### Log

I get the following log:

     [1/7/2021, 1:38:17 PM] [PC] Error: Command failed: sudo wget http://192.168.1.109:5001

    We trust you have received the usual lecture from the local System
    Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

    sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an   askpass helper

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
    killed: false,
    code: 1,
    signal: null,
    cmd: 'sudo wget http://192.168.1.109:5001',
    stdout: '',
    stderr: '\n' +
      'We trust you have received the usual lecture from the local System\n' +
      'Administrator. It usually boils down to these three things:\n' +
      '\n' +
      '    #1) Respect the privacy of others.\n' +
      '    #2) Think before you type.\n' +
      '    #3) With great power comes great responsibility.\n' +
      '\n' +
      'sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure    an askpass helper\n'
  }
  [1/7/2021, 1:38:17 PM] [PC] Waiting for shutdown grace time (15000ms) for "PC" (192.168.1.109)
  [1/7/2021, 1:38:17 PM] [PC] Got state request for "PC" (192.168.1.109): Shutting Down
  [1/7/2021, 1:38:18 PM] [PC] Got state request for "PC" (192.168.1.109): Shutting Down

**Comment by AlexGustafsson** [comment]
The error you're facing is visible in the logs:

```
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure    an askpass helper\n'
```

You can not use sudo non-interactively very easily. In this case, there's no reason to use sudo at all. Simply use `wget http://192.168.1.109:5001` instead.

If you have further issues, please head to [the discussions](https://github.com/AlexGustafsson/homebridge-wol/discussions) instead as issues are now for bugs etc. See https://github.com/AlexGustafsson/homebridge-wol/discussions/132.

Closing.
