### ISSUE TITLE
Implement a way to run wake up commands without trying wake on lan

### ISSUE THREAD

**Issue by UnbendableStraw** [AlexGustafsson/homebridge-wol#149]
### General idea
I'm using this plugin not to actually power machines on and off, but run either on.bat or off.bat. It works as expected when running the off command, but there are minor issues trying to use this exclusively to run commands for the on switch

a) if you don't enter the wake on lan config (i.e. mac address) the on command always fails because no WOL config was present

b) if you do enter wake on lan info it will try to send the magic packet first, then run my on command

It would be nice to see wake on lan info not required and when not provided to try running the off command anyways

**Comment by AlexGustafsson** [comment]
This should already work. See the following part of the README:

| Key | Description |
| --- | ------------|
| mac | The device's MAC address - used to send Magic Packets. Allows any format such as `XX:XX:XX:XX:XX:XX` or `XXXXXXXXXXXX` |
| broadcastAddress | The broadcast address to use when sending the Wake on LAN packet |
| startCommand | Command to run in order to start the machine |
| startCommandTimeout | Timeout for the start command in seconds. Use 0 (default) to disable the timeout |
| wakeGraceTime | Number of seconds to wait after startup before checking online status and issuing the `wakeCommand`, default `45` |
| wakeCommand | Command to run after initial startup, useful for macOS users in need of running `caffeinate` |
| wakeCommandTimeout | Timeout for the wake command in seconds. Use 0 (default) to disable the timeout |

By using `startCommand`, your command should be used when "starting" the device.  You should be able to leave the `mac` out.

**Comment by AlexGustafsson** [comment]
Perhaps this should be clarified. If you get it working the way you'd like, could you please give some feedback on how to better explain your use case in the README?

Also, see #148 where the idea is to start gathering common use cases.

**Comment by UnbendableStraw** [comment]
Thank you for the reply! I saw `startCommand` and thought that was my solution, however I might be using it wrong.

When I add a start command to the plugin's config like so; `"startCommand": "sshpass -p 'password' ssh unbendablestraw@192.168.1.241 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 'cmd.exe /c C:\\Users\\UnbendableStraw\\Desktop\\start.bat'",` I get the following error in the homebridge console

```
[3/9/2021, 9:33:13 AM] [Nic Main PC] NetworkDevice awake cycle started for "Nic Main PC" (192.168.1.241)
[3/9/2021, 9:33:13 AM] [Nic Main PC] Attempting to wake up "Nic Main PC" (192.168.1.241)
[3/9/2021, 9:33:13 AM] [Nic Main PC] NetworkDevice "Nic Main PC" (192.168.1.241) went from status "Offline" to "Waking Up"
[3/9/2021, 9:33:13 AM] [Nic Main PC] Attempting to start "Nic Main PC" (192.168.1.241) by sending a WoL packet
(node:13716) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of null
    at NetworkDevice.wake (/homebridge/node_modules/homebridge-wol/lib/network-device.js:185:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3/9/2021, 9:33:14 AM] [Nic Main PC] NetworkDevice "Nic Main PC" (192.168.1.241) went from status "Waking Up" to "Offline"
```

Thus I think I'm stuck with using the `wakeCommand` which results in the original behavior I described

Full plugin config attempting `startCommand`:

```json
{
    "name": "Nic Main PC",
    "ip": "192.168.1.241",
    "mac": "xx-xx-xx-xx-xx-E3",
    "host": "192.168.1.241",
    "pingInterval": 2,
    "pingsToChange": 5,
    "pingTimeout": 1,
    "pingCommand": "nc -vz 192.168.1.241 4028 2>&1 | grep -i 'open'",
    "pingCommandTimeout": 3,
    "startCommandTimeout": 5,
    "wakeGraceTime": 1,
    "wakeCommandTimeout": 5,
    "startCommand": "sshpass -p 'password' ssh unbendablestraw@192.168.1.241 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 'cmd.exe /c C:\\Users\\UnbendableStraw\\Desktop\\start.bat'",
    "shutdownGraceTime": 1,
    "shutdownCommandTimeout": 5,
    "shutdownCommand": "sshpass -p 'password' ssh unbendablestraw@192.168.1.241 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 'cmd.exe /c C:\\Users\\UnbendableStraw\\Desktop\\stop.bat' ",
    "log": true,
    "logPinger": false,
    "debugLog": false,
    "returnEarly": true,
    "accessory": "NetworkDevice"
}
```

**Comment by AlexGustafsson** [comment]
What version of homebridge-wol do ou use?

**Comment by AlexGustafsson** [comment]
Your usage seems correct, but there seems to be a bug here: https://github.com/AlexGustafsson/homebridge-wol/blob/cfed7dbee3e0fde413c67ab5b9d42ec276d85556/lib/network-device.js#L197.

This is fixed in the latest version. Can you try to install the beta (#124)?

**Comment by UnbendableStraw** [comment]
That does the trick! I opted to replace those lines in network-device.js and that seems to do the trick. 

I was on 1.3.2 and I just updated to 1.3.3 and its still working fine : ) Thank you!
