### ISSUE TITLE
use of "Computer" as accessory name conflicts with homebridge-pc-volume

### ISSUE THREAD

**Issue by Bluebie** [AlexGustafsson/homebridge-wol#17]
homebridge-wol also uses Computer, making it confusing or maybe impossible to try and configure a homebridge setup with both pc-volume and wol installed.

see also https://github.com/JosephDuffy/homebridge-pc-volume/issues/2

**Comment by AlexGustafsson** [comment]
I'm willing to change, however I can't seem to find a good replacement. My train of thought went a bit like this when naming the accessories; WoL is used by computers and the plugin was focused on turning on and off computers. However, now, after recent (and pending) updates, the plugin is much more general. It handles any device and support much more than WoL. 

What do you suggest it should be named instead?

Also, thank you for bringing this to my attention. I've been waiting for this moment given how vague 'Computer' is.

**Comment by JosephDuffy** [comment]
Hi, I'm the developer of homebridge-pc-volume. You used "Computer" first and I was worried that I might have trodden on someone's toes, so I'm happy to change  :) I'm thinking that "Computer-Speakers" would work for homebridge-pc-volume. Feel free to change yours, too, but I'm be updating it for homebridge-pc-volume as part of a 1.0.

**Comment by AlexGustafsson** [comment]
@JosephDuffy, no worries. I'm likely to change as well now that this issue was brought to my attention. It will however take a few days to push alongside some pending updates.

**Comment by AlexGustafsson** [comment]
The beta has now finally been merged, making "Computer" "NetworkDevice" instead.
