### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by technikosoldat** [AlexGustafsson/homebridge-wol#183]
Hello, thank you for this superb plugin. I have a request to make: when adding a device, is it possible to add a tab to indicate the type of device in order to have different icons on Homekit, other than the switch? Thanks

**Comment by AlexGustafsson** [comment]
Hi, thank you for the kind words. There's an issue tracking it here: #123. I'm closing this issue in favor of that one. The feature would be accepted if someone contributes it as I don't have the time to do it myself.
