### ISSUE TITLE
Configuration for win 10

### ISSUE THREAD

**Issue by mafyata** [AlexGustafsson/homebridge-wol#197]
Hi, I am new at this plugin page. I have homebridge on raspberry. I have installed the plugin, see the status of my pc, but can't wake up and shut down via homebridge/homekit. My pc is running windows 10 with local user, not microsoft account.
Where is my mistake?
{
            "name": "Fractal Design",
            "host": "**.*.*.***",
            "pingInterval": 2,
            "pingsToChange": 5,
            "pingTimeout": 1,
            "pingCommandTimeout": 0,
            "mac": "**:**:**:**:**:**",
            "startCommandTimeout": 0,
            "wakeGraceTime": 45,
            "wakeCommandTimeout": 0,
            "shutdownGraceTime": 15,
            "shutdownCommandTimeout": 0,
            "logLevel": "Info",
            "returnEarly": false,
            "accessory": "NetworkDevice",
            "shutdownCommand": "net rpc shutdown --ipaddress 10.0.1.190 --user myuser%mypass"
        }

LOG:
[3/9/2022, 2:19:35 PM] [Fractal Design] [NetworkDevice] Shutdown cycle started
[3/9/2022, 2:19:35 PM] [Fractal Design] [NetworkDevice] Device went from status "Online" to "ShuttingDown"
[3/9/2022, 2:19:35 PM] [Fractal Design] [NetworkDevice] Attempting to shut down the device using "net"
[3/9/2022, 2:19:35 PM] [Fractal Design] [NetworkDevice] HWOL-4001 An error occured while trying to shut down the device. This is most likely not an issue with homebridge-wol itself. For more information see https://github.com/AlexGustafsson/homebridge-wol/wiki/Frequently-Asked-Questions#hwol-4001
[3/9/2022, 2:19:35 PM] [Fractal Design] [NetworkDevice] Waiting for shutdown grace time (NaNms)
[3/9/2022, 2:19:50 PM] [Fractal Design] [NetworkDevice] Device went from status "ShuttingDown" to "Online"

**Comment by AlexGustafsson** [comment]
The error message tells us the following things:

> HWOL-4001 An error occured while trying to shut down the device. This is most likely not an issue with homebridge-wol itself. For more information see https://github.com/AlexGustafsson/homebridge-wol/wiki/Frequently-Asked-Questions#hwol-4001

This is a common error and does not have to do with the plugin itself, please refer to the link included in the log: https://github.com/AlexGustafsson/homebridge-wol/wiki/Frequently-Asked-Questions#hwol-4001.

> [3/9/2022, 2:19:35 PM] [Fractal Design] [NetworkDevice] Waiting for shutdown grace time (NaNms)

For some reason your shutdown grace time is not parsing correctly (`NaN` = `Not a Number`), but your configuration looks good (`shutdownGraceTime: 45`).

**Comment by MarvelDc97** [comment]
Try opening Terminal in Homebridge and typing "sudo apt-get install samba-common-bin"
I was having the same issue as you until I did this and restarted Homebridge.

**Comment by mafyata** [comment]
Thanks, this work for me :) 
Do you know how to remove this when I try to shutdown via the homekit? This make my pc to turn off longer time.
![IMG_2462](https://user-images.githubusercontent.com/48009267/159117596-caa179e6-e370-4dd9-9823-90dd7148f5ba.jpg)
.

**Comment by AlexGustafsson** [comment]
@MarvelDc97 thanks for helping out!

@mafyata, looks like you could specify the `-f` flag to force shutdown. Here's the manual: https://www.samba.org/samba/docs/current/man-html/net.8.html.

I'm closing this issue as it's been solved, but feel free to come back here and update the issue if you're able to find a solution for the dialog being shown.
