### ISSUE TITLE
Windows Shutdown Command

### ISSUE THREAD

**Issue by mehtaman** [AlexGustafsson/homebridge-wol#20]
Hi,

I tried to use the below as a shutdown command but it does not work:
"shutdownCommand": "shutdown -f -r t 0"

What would be the correct way to parse through the command from a Pi to Windows system?

**Comment by AlexGustafsson** [comment]
The command is run as the same user as is running the Homebridge server. Is that user allowed to shutdown the system? Also, aren't you supposed to add a dash to 't' (-t 0)? Otherwise I can't seem to find any issues.

**Comment by mehtaman** [comment]
Ah thanks for spotting the typo!
I'll give that a go and see how it runs.

**Comment by AlexGustafsson** [comment]
Did you end up solving it?

**Comment by mehtaman** [comment]
Thanks @AlexGustafsson, it was just the typo :+1:
