### ISSUE TITLE
Is this supporting also Wake on WLAN?

### ISSUE THREAD

**Issue by stich86** [AlexGustafsson/homebridge-wol#24]
can I wake up a device over WLAN?
thanks!

**Comment by AlexGustafsson** [comment]
This is supported by the plugin, however it is highly hardware and software dependant. Your wireless network interface needs to support it and your OS needs to be set up to allow the hardware to be awake and accepting the so called magic packets.

This is called "Wake on WLAN" or "WoWLAN". By googling on how to set it up you may find more information.

Here's a link that seems to describe the process if you're in a Windows 10 PC.

Good luck!
