### ISSUE TITLE
Please add icons if possible

### ISSUE THREAD

**Issue by and43a** [AlexGustafsson/homebridge-wol#240]
### General idea

beautiful app, well done and working. it would be great to have the ability to change the icons based on how you use them.

### Use case

a new look

**Comment by AlexGustafsson** [comment]
If you're thinking of being able to specify other icons in the home app, it would probably fall under #123. It would allow you two specify your device to be a "router", for example. If you're thinking of the Homebridge UI, you'll probably have to open an issue there to discuss changing icons. Closing.
