### ISSUE TITLE
Windows PC does not wake up

### ISSUE THREAD

**Issue by det-box** [AlexGustafsson/homebridge-wol#25]
Hello,
since version 3. 0. 0 no longer awakes the WINPC on
here the config:
`  {
            "accessory": "NetworkDevice",
            "name": "PC-Det",
            "mac": "C8:60:00:14:98:B4",
            "ip": "192.168.23.211",
            "pingInterval": 45,
            "wakeGraceTime": 90,
            "shutdownGraceTime": 60,
            "shutdownCommand": "net rpc shutdown -f -t 60 -I 192.168.23.211 -U xxxx%xxx"
        },
`
with version 2. 1. 0 and other accessory-name it worked.
Please fix
Thank you

Edit:
I use
node 8. 4. 0
npm 5. 4. 1

**Comment by AlexGustafsson** [comment]
Could you please attach your log as well as full configuration?

**Comment by AlexGustafsson** [comment]
There was a simple mistake in the code not caught by us. Thank you for posting the issue. You'll have to update to 3.0.1 to receive the fix.

Fixed in [3.0.1](https://github.com/AlexGustafsson/homebridge-wol/commit/46c12a0e74a4a61e846885f98d1c2939b0ad4852).

**Comment by det-box** [comment]
Thank you,
now ok
