### ISSUE TITLE
Dont wake after shutdown

### ISSUE THREAD

**Issue by Lechucico** [AlexGustafsson/homebridge-wol#259]
### Issue

I will explain it in the best possible way:

The computer can ALWAYS be turned on if I turn it off manually. If I turn it off using this plugin, It can't turn it on. I have been able to verify that this is most probably plugin's fault, because if I run the SSH command to turn it off manually, the plugin can then turn on the PC.

I am going to pass a series of LOGS that I have been able to compile proving that it is the fault of this plugin:

These logs are from when I shut down the computer with homebridge:

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/c53cfa2f-2341-469e-8540-648ad51c9111)

The problem comes, that the plugin stays stuck until I don't turn PC on manually, which is when the log that I mark below appears:

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/dd035092-0da3-4f80-ba70-244754e60df2)

Until the "Waiting for shutdown grace time" appears, the plugin becomes unresponsive, and it doesn't appear until I turn on the PC manually. No matter how much I click on the homekit switch to turn on the computer, no logs appear.

If I turn the PC off manually, I can turn it on and the logs appear as they should:

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/12977034-a63e-4eee-9207-eac51d12624b)

See if anyone can help me.

### Environment

```Markdown
- os and os version: Raspbian GNU/Linux Bullseye (11)
- node version: 20.10.0
- homebridge version: 1.7.0
- homebridge-wol version: 6.0.1
```

### Configuration

{
    "name": "Ordenador",
    "manufacturer": "homebridge-wol",
    "model": "NetworkDevice",
    "host": "192.168.5.136",
    "pingInterval": 5,
    "pingsToChange": 1,
    "pingTimeout": 1,
    "pingCommandTimeout": 0,
    "mac": "XX:XX:XX:XX:XX:XX",
    "broadcastAddress": "192.168.5.255",
    "startCommand": "wakeonlan XX:XX:XX:XX:XX:XX",
    "startCommandTimeout": 0,
    "wakeGraceTime": 30,
    "wakeCommandTimeout": 0,
    "shutdownCommand": "ssh lechucico@192.168.5.136 shutdown -h",
    "shutdownGraceTime": 30,
    "shutdownCommandTimeout": 0,
    "logLevel": "None",
    "returnEarly": true,
    "accessory": "NetworkDevice"
}

**Comment by Jamyz** [comment]
@Lechucico in english but i understand spanish.
Maybe the plugin shutdown totally the computer when you turn off. When you turn off manually maybe he use sleep or hibernate mode, if why you can wake up. I suspect drivers ethernet or motherboard drivers. 
Can you try change:
`"shutdownCommand": "ssh lechucico@192.168.5.136 shutdown -s",`
or
`"shutdownCommand": "ssh lechucico@192.168.5.136 shutdown -s now",`
or
`"shutdownCommand": "ssh lechucico@192.168.5.136 pm-suspend",`
If change something.

**Comment by Lechucico** [comment]
@Jamyz I always hibernate PC when I'm doing this manually. The command that I use is `ssh lechucico@192.168.5.136 shutdown -h`, it's the equivalent for hibernate. Also, If I execute this command through homebridge terminal, the plugin can still wake up PC, so it can't be this ssh command.

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/5b897e98-d4f6-4464-9f99-7d1982e0557a)

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/80f997c2-3781-4bdd-90f0-bf14b58a086b)

**Comment by Jamyz** [comment]
I have one day the same problem because one computer afetr shutdown cant wake up because totally shutdown. And dont have S1 or S3 state to wake. So i don't no. Hope you find soon.

**Comment by Lechucico** [comment]
I think the problem must be here:

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/3c3a1abc-5540-49b9-a7dc-0ce85e3d78c4)

I'll have to check how to hibernate with delay, because shutdown -h -t 2 is not available on default shutdown command

**Comment by Jamyz** [comment]
Why use ssh under windows ? Why not try with net rpc shutdown ?
like this for you.
In "Shutdown configuration" put 
net rpc shutdown --ipaddress 192.168.5.136 --user UserNameWindows%PasswordUserWindows
Have you the same issue ?

**Comment by Lechucico** [comment]
> ![image](https://private-user-images.githubusercontent.com/22009615/301488295-3c3a1abc-5540-49b9-a7dc-0ce85e3d78c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODgwNzgsIm5iZiI6MTcwNjc4Nzc3OCwicGF0aCI6Ii8yMjAwOTYxNS8zMDE0ODgyOTUtM2MzYTFhYmMtNTU0MC00OWI5LWE3ZGMtMGNlODVlM2Q3OGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDExNDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZmE0ODUwNDMyOWJiNTgyYzI4NGY1MTRkYTllNzQ4NTBiMjY0ZTkzYzIxYWEyNTcxYjg1MDAwYzQ5NmI2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XGpN9sYrxTd1WyH5iVgxoaqs17kyp-i4-Nw_2wfV3Zw)
> 

The problem was here, solved adding a delay:

![image](https://github.com/AlexGustafsson/homebridge-wol/assets/22009615/da68e05c-48cb-4ad1-9be2-90054d47c425)
