### ISSUE TITLE
It looks like wake-on-lan option is not working anymore

### ISSUE THREAD

**Issue by ericsboro** [AlexGustafsson/homebridge-wol#26]
"accessory": "NetworkDevice",
                        "name": "Server",
                        "mac": "xx:xx:xx:xx:xx:xx",
                        "ip": "1x.x.x.x",
                        "pingInterval": 45,
                        "wakeGraceTime": 90,
                        "shutdownGraceTime": 15,
                        "shutdownCommand": "ssh admin@10.0.1.3 /Users/admin/shutdown.sh",
                        "log": true

**Comment by AlexGustafsson** [comment]
Please make sure you're using 3.0.1 as 3.0.0 contained a regression.

**Comment by ericsboro** [comment]
actually I have 3.0.1 installed.
homebridge version is 0.4.27.

any suggestions?

**Comment by AlexGustafsson** [comment]
Start homebridge with 'DEBUG=* homebridge --debug' and post the full log. There's no longer any confirmed regression in 3.0.1 so there could be a local issue.

**Comment by ericsboro** [comment]
Hi there!

I discovered that if i'm starting homebridge with report pc turned off — switch is turning remote pc on without any issue [9/11/2017, 10:06:37 PM in the log below], but later i turned off remote pc at [9/11/2017, 10:10:16 PM] homebridge seems cannot read pc state and don't realize that it's down - thus not sending wol MagicPackage.

root@smarthome:~# DEBUG=* homebridge --debug
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[9/11/2017, 10:06:26 PM] Loaded plugin: homebridge-wol
[9/11/2017, 10:06:26 PM] Registering accessory 'homebridge-wol.NetworkDevice'
[9/11/2017, 10:06:26 PM] ---
[9/11/2017, 10:06:26 PM] Loaded config.json with 1 accessories and 0 platforms.
[9/11/2017, 10:06:26 PM] ---
[9/11/2017, 10:06:26 PM] Loading 1 accessories...
[9/11/2017, 10:06:26 PM] [Server] Initializing NetworkDevice accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 012-34-567 │     
    └────────────┘     
                       
  EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /pair-verify +90ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +0ms
  HAPServer [CC:22:3D:E3:CE:30] Client 9F0E15A6-88E5-4C8E-ADE2-D674A6882068 verification complete +3ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /accessories +10ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /characteristics +290ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"ev":true}] +3ms
  Accessory [Homebridge] Registering Characteristic "On" for events +2ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /characteristics?id=4.10 +446ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /characteristics?id=4.10 +1ms
  Accessory [Homebridge] Getting value for Characteristic "On" +10ms
  Accessory [Homebridge] Got Characteristic "On" value: false +1ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /characteristics +8s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"value":1}] +1ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +1ms
[9/11/2017, 10:06:37 PM] [Server] NetworkDevice awake cycle started for "Server" (10.0.1.3)
[9/11/2017, 10:06:37 PM] [Server] Attempting to wake up "Server" (10.0.1.3)
  EventedHTTPServer [::ffff:10.0.1.11] Muting event '4.10' notification for this connection since it originated here. +18ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +4ms
 EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /characteristics +2m
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"value":0}] +3ms
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +0ms
[9/11/2017, 10:08:49 PM] [Server] NetworkDevice shutdown cycle started for "Server" (10.0.1.3)
[9/11/2017, 10:08:49 PM] [Server] Attempting to shut down "Server" (10.0.1.3) using "ssh admin@10.0.1.3 /Users/admin/shutdown.sh"
  EventedHTTPServer [::ffff:10.0.1.11] Muting event '4.10' notification for this connection since it originated here. +24ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +10ms
  EventedHTTPServer [::ffff:10.0.1.11] Sending HTTP event '4.10' with data: {"characteristics":[{"aid":4,"iid":10,"value":true}]} +684ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /characteristics?id=4.10 +1m
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /characteristics?id=4.10 +1ms
  Accessory [Homebridge] Getting value for Characteristic "On" +9ms
  Accessory [Homebridge] Got Characteristic "On" value: true +1ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /characteristics +10s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"value":0}] +3ms
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +2ms
[9/11/2017, 10:10:16 PM] [Server] NetworkDevice shutdown cycle started for "Server" (10.0.1.3)
[9/11/2017, 10:10:16 PM] [Server] Attempting to shut down "Server" (10.0.1.3) using "ssh admin@10.0.1.3 /Users/admin/shutdown.sh"
  EventedHTTPServer [::ffff:10.0.1.11] Muting event '4.10' notification for this connection since it originated here. +20ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +2ms
[9/11/2017, 10:10:19 PM] [Server] An error occured while trying to shut down "Server" (10.0.1.3): Error: Command failed: ssh admin@10.0.1.3 /Users/admin/shutdown.sh
ssh: connect to host 10.0.1.3 port 22: No route to host

  EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /characteristics +5s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"value":1}] +5ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +1ms
  EventedHTTPServer [::ffff:10.0.1.11] Muting event '4.10' notification for this connection since it originated here. +1ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /characteristics +2s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"value":0}] +1ms
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +0ms
[9/11/2017, 10:10:24 PM] [Server] NetworkDevice shutdown cycle started for "Server" (10.0.1.3)
[9/11/2017, 10:10:24 PM] [Server] Attempting to shut down "Server" (10.0.1.3) using "ssh admin@10.0.1.3 /Users/admin/shutdown.sh"
  EventedHTTPServer [::ffff:10.0.1.11] Muting event '4.10' notification for this connection since it originated here. +7ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP request: /characteristics +2s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":10,"value":1}] +0ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +1ms
  EventedHTTPServer [::ffff:10.0.1.11] Muting event '4.10' notification for this connection since it originated here. +1ms
  EventedHTTPServer [::ffff:10.0.1.11] HTTP Response is finished +0ms
[9/11/2017, 10:10:26 PM] [Server] An error occured while trying to shut down "Server" (10.0.1.3): Error: Command failed: ssh admin@10.0.1.3 /Users/admin/shutdown.sh
ssh: connect to host 10.0.1.3 port 22: No route to host

^C[9/11/2017, 10:10:31 PM] Got SIGINT, shutting down Homebridge...

**Comment by ericsboro** [comment]
in addition i uninstalled all other packages and cleaned-up config.json

**Comment by AlexGustafsson** [comment]
Thank you for your help! I'll try to replicate.

Just to make sure, the error mentioned at the bottom of your log is not what you've experienced before, right? (It's not related to the plugin itself).

**Comment by ericsboro** [comment]
Correct — in the past everything worked properly.
For just in case — homebridge installed on "apple tv gen 1 with OSMC onboard (Linux smart 4.2.3-25-osmc #1 Tue Jun 6 17:37:42 UTC 2017 i686 GNU/Linux) and remote pc I need to shutdown and start — Mac OS X (Hackintosh) installed on Dell desktop.

**Comment by AlexGustafsson** [comment]
I just edited my initial comment, but I'll post it again for clarification.

Please make sure that the machine running homebridge can in fact ping the device you're trying to start and shut down.

**Comment by ericsboro** [comment]
i confirm that each device can ping each other. both are located in 10.0.1.0/24 network.

**Comment by AlexGustafsson** [comment]
The bug is confirmed. 

Steps to replicate:

1. Turn off the device manually.
2. Setup a NetworkDevice with `mac`, `ip` and `shutdownCommand` in config.json and start homebridge.
3. Turn the device on via homebridge
4. Turn the device off via homebridge
5. Try to turn the device on via homebridge. Fail

**Comment by AlexGustafsson** [comment]
I can no longer replicate the bug with the newly released 3.1.0. Try that version.
If it doesn't solve your issue, please post the log from running `DEBUG=* homebridge` and turning the device on and off a couple of times.

**Comment by ericsboro** [comment]
I confirm, issue resolved!

Many thanks for prompt fix!
