### ISSUE TITLE
Power switch not staying on

### ISSUE THREAD

**Issue by damianromanowski** [AlexGustafsson/homebridge-wol#3]
Seems like the switch is resetting itself back to the off state even thought the computer is still on.

Line 38-40:
```javascript
setTimeout(function() {
  this._service.setCharacteristic(Characteristic.On, false);
}.bind(this), 30000);
```

Any particular reason that is there? Why not leave the switch on, it already assumes that the wol packet was sent successfully. Maybe run a periodic ping to set the actual state?

**Comment by AlexGustafsson** [comment]
That "feature" was a placeholder for upcoming features I never got around to implement. Luckily @blubber did all the improvements I hoped to make and they are now a part of the main repo. Be sure to update the package and re-read the documentation to get updated on any news.
