### ISSUE TITLE
The wake and shutdown command may reveal secrets used

### ISSUE THREAD

**Issue by AlexGustafsson** [AlexGustafsson/homebridge-wol#36]
### Backstory
It has come to my attention that some wake and shutdown commands (such as `net rpc ...`) may need username and passwords in the command itself. SSH, for example allows for the sensible solution to use key authentication - but not all commands may allow such a workaround. Since the current version of homebridge-wol may log the commands being used, these username and passwords may be visible in the terminal output or a log file. 

### Issue
[This line](https://github.com/AlexGustafsson/homebridge-wol/blob/master/lib/network-device.js#L150) logs the wake command which may contain secrets such as a username and or password.

[This line](https://github.com/AlexGustafsson/homebridge-wol/blob/master/lib/network-device.js#L161) logs the shutdown command which may contain secrets such as a username and or password.

### Environment
* homebridge-wol version: 3.2.2

### Notes
A possible solution is to extract the first word and log only that, which may result in logs such as:
> Attempting to wake up "My Windows PC" (192.168.1.151) using "net"

instead of

> Attempting to wake up "My Windows PC" (192.168.1.151) using "net rpc shutdown --ipaddress 192.168.1.151 --user alex%1234"

Another solution would be to omit all details about the command used.

This issue is great for anyone that may have just started out in open source and or javascript.

**Comment by TheChallinor** [comment]
Do you enter username % password with no space then?

so username%password 

Shutdown is not working for me at the moment.

**Comment by AlexGustafsson** [comment]
@TheChallinor Yes - there’s no space between. Try to look through the FAQ section as well as other issues for common mistakes. If your issue persists, please open up a separate issue, following the template provided there. Good luck!

**Comment by TheChallinor** [comment]
Had a good look, it boots up fine but sadly does not shut down remotely. 

Something going on as I have to RDC onto the PC in order to log it on.

**Comment by AlexGustafsson** [comment]
@TheChallinor Open up a new issue and follow the template. Make sure to include logs.

**Comment by AlexGustafsson** [comment]
Fixed by only printing the command's name (i.e. first word in string).
