### ISSUE TITLE
Designing a new logo

### ISSUE THREAD

**Issue by AlexGustafsson** [AlexGustafsson/homebridge-wol#48]
Not too long ago I updated the README to a simpler to read and more consistent layout. This process included adding a logo for the project;

![Current logo](https://github.com/AlexGustafsson/homebridge-wol/raw/master/.github/logo.png)

The logo works, but isn't especially pretty.

Your task is to create a new logo displaying a trait of the wake on lan nature of the project, as well as its name (homebridge-wol).

The current logo can be found in the [.github](https://github.com/AlexGustafsson/homebridge-wol/tree/master/.github) folder as `logo.png` and `logo.psd`. The new logo should have the same dimensions and preferably (not required) have a source which can be shared.

Unless otherwise noted, the created logo will fall under the same license as the project and will be used in the README.

**Comment by gcarlosr** [comment]
Hi I am a graphic designer and I would like to help this issue by contributing with design according to what you need, I would like to know more about what your project is about and where the design selected only on Github or on a specific web including favicon icon will appear. ? Leave me your comments to inform me more about your project.

**Comment by AlexGustafsson** [comment]
Hi!

I feel like it’s fair to first mention that this will have to be unpaid work as I do not monetise the project in any way. It’s completely understandable if you would like to spend your time otherwise due to that.

The project is a home automation plugin for a project itself called Homebridge. Homebridge connects third-party plugins like this to Apple’s HomeKit service, providing built in home automation capabilities in iOS - including use with Apple’s AI Siri.

The plugin allows users to add network devices such as computers and servers to HomeKit and control them by turning them on and off as well as check their current status. This plugin’s function is partly provided by the Wake On LAN (wol) protocol, hence the name. Due do HomeKit’s automation capabilities this allows for a series of events such as “turn the computer off when I leave the house”. It also allows for controlling your computer with Siri commands such as “turn my computer on”.

The overall traits of the project are therefore networking, home automation and controllability (on/off).

As of now this project will not be made further available on the web (in form of a website) and as such the only place the image would be visible is in the README, in place of the currently used image.

**Comment by EternalRZ** [comment]
Hello! I was just curious, is a logo design still needed?

**Comment by AlexGustafsson** [comment]
Hi @EternalRZ! Yes. Be sure to read the comment above yours for clarification.

**Comment by HenrySeed** [comment]
I was thinking something like this would work? (I think it looks ok without the text)
![Screen Shot 2020-03-17 at 10 54 26 PM](https://user-images.githubusercontent.com/5369727/76844561-58add780-68a2-11ea-87c3-1a225debd8ed.png)
![Screen Shot 2020-03-17 at 10 59 24 PM](https://user-images.githubusercontent.com/5369727/76844964-f7d2cf00-68a2-11ea-937b-385f79d68695.png)

**Comment by AlexGustafsson** [comment]
@HenrySeed Looks great! Is this original content?

**Comment by HenrySeed** [comment]
Yeah absolutely, just whipped it up in illustrator. I tried to incorporate the I/O power switch but couldn't get it to work right. I'll do some more tweaking tomorrow and export a high-res one for the readme.

**Comment by HenrySeed** [comment]
I made a couple more logos, Do you have a preference? I cant really decide on the best.
![Screen Shot 2020-03-18 at 8 03 47 AM](https://user-images.githubusercontent.com/5369727/76892133-0a72f580-68ef-11ea-847e-986d85ff3091.png)

**Comment by AlexGustafsson** [comment]
I think they all look great and all have their merits. I like the last one especially since it integrates well with the buttons in HomeKit. I think it's up to you, but if you really can't decide, the last one looks fun!

**Comment by HenrySeed** [comment]
Ive opened a new pull request with the changes. Let me know if i've made any mistakes.
https://github.com/AlexGustafsson/homebridge-wol/pull/100

**Comment by AlexGustafsson** [comment]
Great! Closing this issue.
