### ISSUE TITLE
Ping Problem status

### ISSUE THREAD

**Issue by giuse93or** [AlexGustafsson/homebridge-wol#51]
Hey Alex, I’m not able to see the status of my windows pc from the home app
I set extra permiss in service section of Homebridge’s unit file
I’m able to wake up the pc, but I’m not able to shutdown
I’m sure that the ip is correct, and with an other app in my iphone i can see the status from the ping

I don't care to turn ff my pc, but I want to see if is online or not

Can you help me please?

### Environment
Raspberry Raspian GNU/Linux 9 (stretch)
Node version v8.12.0
Homebridge version 0.4.45
Homebridge-wol version: latest (I’ve installed your plugin last Monday so i think it’s 3.2.4, but I don’t know I can verify)

### Configuration
My configuration looks like this:
{
        "bridge": {
                "name": "Raspberry",
                "username": "AC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "123-45-123"
        },
        "description": "",
        "accessories": [
         {
          "accessory": "NetworkDevice",
          "name": "Computer Vibox",
          "mac": " <mac-address> ",
          "ip": "192.168.1.35",
          "shutdownCommand": "net rpc shutdown --ipaddress 192.168.1.35 --user *username%*password"
         }
        ],
        "platforms": []
}

### Log
When I follow these steps:
1. Run `DEBUG=* homebridge`
2. Let it run for five minutes
3. Tap a switch
4. Wait one minute
5. Tap the same switch

I get the following log:
`DEBUG=* homebridge`
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:128:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:97:10)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
-bash: [2018-11-8: command not found

**Comment by giuse93or** [comment]
sudo systemctl status homebridge
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-11-06 14:34:01 UTC; 1 day 21h ago
 Main PID: 23566 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─23566 homebridge

Nov 08 11:04:54 raspberrypi homebridge[23566]: [2018-11-8 11:04:54] [Computer Vibox] Attempting to wake up "Computer Vibox" (192.168.1.35)
Nov 08 11:04:54 raspberrypi homebridge[23566]: [2018-11-8 11:04:54] [Computer Vibox] NetworkDevice "Computer Vibox" (192.168.1.35) went from status "Offline" to "Waking Up"
Nov 08 11:05:40 raspberrypi homebridge[23566]: [2018-11-8 11:05:40] [Computer Vibox] NetworkDevice "Computer Vibox" (192.168.1.35) went from status "Waking Up" to "Offline"
Nov 08 11:37:19 raspberrypi homebridge[23566]: [2018-11-8 11:37:19] [Computer Vibox] NetworkDevice awake cycle started for "Computer Vibox" (192.168.1.35)
Nov 08 11:37:19 raspberrypi homebridge[23566]: [2018-11-8 11:37:19] [Computer Vibox] Attempting to wake up "Computer Vibox" (192.168.1.35)
Nov 08 11:37:19 raspberrypi homebridge[23566]: [2018-11-8 11:37:19] [Computer Vibox] NetworkDevice "Computer Vibox" (192.168.1.35) went from status "Offline" to "Waking Up"
Nov 08 11:38:05 raspberrypi homebridge[23566]: [2018-11-8 11:38:05] [Computer Vibox] NetworkDevice "Computer Vibox" (192.168.1.35) went from status "Waking Up" to "Offline"
Nov 08 11:56:03 raspberrypi homebridge[23566]: [2018-11-8 11:56:03] [Computer Vibox] NetworkDevice awake cycle started for "Computer Vibox" (192.168.1.35)
Nov 08 11:56:03 raspberrypi homebridge[23566]: [2018-11-8 11:56:03] [Computer Vibox] Attempting to wake up "Computer Vibox" (192.168.1.35)
Nov 08 11:56:03 raspberrypi homebridge[23566]: [2018-11-8 11:56:03] [Computer Vibox] NetworkDevice "Computer Vibox" (192.168.1.35) went from status "Offline" to "Waking Up"

it don't try to shutdown the pc

**Comment by AlexGustafsson** [comment]
I've published 3.2.5 to NPM which contains many fixes. If it does not solve your issue, feel free to reopen the issue.

Closing.
