### ISSUE TITLE
Limit pinginterval logging

### ISSUE THREAD

**Issue by hossame** [AlexGustafsson/homebridge-wol#6]
Hello,

Great plugin! I am utilizing the ping interval feature and wish to keep it at a short duration, but don't want my logs to grow to humongous proportions.

Can there be a way to limit the logging to hide all of the "Pinging x.x.x.x" entries but still keep the other logging entries as they are?

Thanks!

**Comment by blubber** [comment]
I was thinking of removing the ping logging altogether, it is not adding that much usable information anyway. Also I've added it for debugging purposes.

**Comment by hossame** [comment]
Great, thanks very much. Looking forward to it.
