### ISSUE TITLE
Shutdown ssh Macosx password required

### ISSUE THREAD

**Issue by yceballost** [AlexGustafsson/homebridge-wol#66]
### Issue
I can't shutdown my PC because I need to include password in my command.

### Configuration
```
"accessories": [
{
      "name" : "Hackintosh",
      "accessory" : "NetworkDevice",
      "pingInterval" : 45,
      "mac" : "<mac-address>",
      "ip" : "192.168.1.35",
      "wakeGraceTime" : 10,
      "wakeCommand" : "ssh yayo@192.168.1.35 caffeinate -u -t 300",
      "shutdownCommand" : "ssh yayo@192.168.1.35 sudo shutdown -h now",
      "shutdownGraceTime" : 15
    },
```

I just try to use the shutdownCommand that I'm using in config.json in terminal and password required.

**Comment by AlexGustafsson** [comment]
Please setup SSH key authentication as recommended in the README. This is not an issue with the package itself, rather a UNIX one.

There are many resources that guide you through the process. Here’s one: https://www.linode.com/docs/security/authentication/use-public-key-authentication-with-ssh/
