### ISSUE TITLE
Shutdown Command to Windows 10 PC dont work in Synology Docker Container

### ISSUE THREAD

**Issue by Kallitho** [AlexGustafsson/homebridge-wol#75]
**I just want to use this Plugin to control my Windows 10 PC for remote Start/Shutdown.**

I run Homebridge in a Synology Docker Container.

The WOL Command works perfect, but what i have to configure exactly to make the following Shutdown command work in the Home App? 
`net rpc shutdown -I 192.168.1.48  -U User%Password`
_(And yes on Windows everything is configured correctly: Create a new LOCAL User with Admin Rights | Create the Policy Key in the Registry)_

I installed this [Samba Package](https://hub.docker.com/r/dperson/samba/) with **no further** configuration. Is this the right one?

Now important:
- If i directly copy the Shutdown Command into the Terminal of the Samba Container-->it Works and a second later my Windows PC starts the Shutdown Procedere:
      -->it shows: The Shutdown Command itself works fine,it is correctly send via the LAN from my NAS to the PC and Windows processes the command correctly!
![image](https://user-images.githubusercontent.com/54825661/64340342-37f8f100-cfe6-11e9-95be-b19cb3556a5a.png)
- if i directly copy the Shutdown Command into the Terminal of the Homebridge Container (where i need it of course)-->It doesnt work: _(No Reaction in Apple Home App)_
![image](https://user-images.githubusercontent.com/54825661/64340364-4c3cee00-cfe6-11e9-8b4c-5ef8769a6c6c.png)

my config.json:

> "accessories": [{
			"accessory": "NetworkDevice",
			"name": "Toms-Windows-PC",
			"mac": "xx:xx:xx:xx:xx:xx",
			"ip": "192.168.1.48",
			"shutdownCommand": "net rpc shutdown -I 192.168.1.48  -U User%Password"
		},

**What is missing in my hole Configuration? I think the 2 Containers need to communicate with each other, so do i have to link them?? But i have no idea how to do this haha.**

**Comment by AlexGustafsson** [comment]
If not strictly allowed, docker containers are unable to communicate with each other. You will have to ensure that the containers share a network. You should probably read https://docs.docker.com/v17.09/engine/userguide/networking/default_network/container-communication/.

Unfortunately this is out of scope for this plugin and if you need further assistant I would like to redirect you to a forum such as StackOverflow.

I will close the issue for now. If you resolve the issue, please write a comment about your solution for others to use in the future!
