### ISSUE TITLE
Heartbeat from a VLAN

### ISSUE THREAD

**Issue by AlfaJackal** [AlexGustafsson/homebridge-wol#79]
Moved my homebridge to another vlan, opened the ICMP from homebridge to my pc, but unfortunately, in HomeKit it is not detected that the PC is switched on. From the same subnet everything worked like a charm.

My configuration looks like this:
```
        {
            "accessory": "NetworkDevice",
            "name": "MasterChief",
            "mac": "xx:xx:xx:xx:xx",
            "ip": "10.10.0.63",
            "pingCommand": "curl -m 2 -s http://10.10.0.63:5001",
            "pingInterval": 15
        },
```

Log does not show anything special:
```
Dez 10 20:43:20 Eggman homebridge[13372]: [10.12.2019, 20:43:20] [MasterChief] Attempting to wake up "MasterChief" (10.10.0.63)
Dez 10 20:43:20 Eggman homebridge[13372]: [10.12.2019, 20:43:20] [MasterChief] NetworkDevice "MasterChief" (10.10.0.63) went from status "Offline" to "Waking Up"
Dez 10 20:44:06 Eggman homebridge[13372]: [10.12.2019, 20:44:06] [MasterChief] NetworkDevice "MasterChief" (10.10.0.63) went from status "Waking Up" to "Offline"
```

I never get a zero here ...
```
pi@Eggman:~ $ curl -m 2 -s 10.10.0.63:5001
pi@Eggman:~ $ echo $?
28
```

Any idea of establishing this connection?

**Comment by AlexGustafsson** [comment]
Curl uses TCP to communicate. It does not send an ICMP package. You will need to configure your network to allow the server running homebridge-wol to send TCP requests on port 50001 to your target device.
