### ISSUE TITLE
Siri responding that some devices aren't responding

### ISSUE THREAD

**Issue by EternalRZ** [AlexGustafsson/homebridge-wol#80]
After updating to the latest version of the plugin, using Siri voice commands to wake up and shut down computers results in Siri returning a response indicating that it needs more time, and then eventually that the device wasn't or isn't responding. Homebridge logs and the device itself however, clearly indicate the command being sent successfully as well as the fact that the device actually ends up turning on or shutting down, despite Siri stating that it didn't. The plugin still works, Siri just doesn't seem to think so even though it executes the commands just fine.

Using the Home App also displays that turning devices on and off also works when tapping on the device's respective tile, so the issue is just Siri being unable to identify whether it's turned the device on or off and just states that the device isn't responding. Siri can still tell if the device is on or off when asking for the status of said device.

I was able to isolate the issue down to this plugin by testing out other plugins, restarting the Homebridge server, and the service itself to remove any possible external issues. I was able to resolve the issue by installing version 3.2.4.

I'd also like to point out that my Homebridge server is a Raspberry Pi 4 with all packages and software up to date.

**Comment by AlexGustafsson** [comment]
What version of Homebridge are you using?

**Comment by EternalRZ** [comment]
Homebridge Version is 0.4.50.

**Comment by AlexGustafsson** [comment]
I've confirmed the bug and it has been fixed in the master branch. Thanks for reporting the issue!

Please try out the master branch of this project and play around. There's no real breaking change but a lot of code has been rewritten which may result in some regressions.

Closing for now.
