### ISSUE TITLE
Plugin /usr/lib/node_modules/homebridge-wol requires Node version of >=11.0.0

### ISSUE THREAD

**Issue by dcaccount** [AlexGustafsson/homebridge-wol#83]
Hello,
after the upgrade to latest version I got following error that is preventing Homebridge from starting:

> Plugin /usr/lib/node_modules/homebridge-wol requires Node version of >=11.0.0 which does not satisfy the current Node version of v8.17.0. You may need to upgrade your installation of Node.

I upgraded to node 11.15.00 but I keep getting the same error as I had not had upgraded.

What can I do?

Thanks for helping, Dan

**Comment by AlexGustafsson** [comment]
Try to uninstall all node versions and then install a newer node version again. It seems like you still have some old version installed. What is the output of running `node -v` in the terminal?

**Comment by dcaccount** [comment]
Hello, thanks for helping. The output is v11.15.0.

How can I uninstall and reinstall a newer version?

**Comment by AlexGustafsson** [comment]
That node version does seem correct. Does Homebridge still produce the same output as you posted above?

**Comment by dcaccount** [comment]
Unfortunately yes, please check:

> [2020-1-2 17:05:27] Plugin /usr/lib/node_modules/homebridge-wol requires Node version of >=11.0.0 which does not satisfy the current Node version of v8.17.0. You may need to upgrade your installation of Node.
[2020-1-2 17:05:27] ====================
[2020-1-2 17:05:27] ERROR LOADING PLUGIN homebridge-wol:
[2020-1-2 17:05:27] /usr/lib/node_modules/homebridge-wol/lib/pinger.js:32
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-wol/lib/network-device.js:4:16)
[2020-1-2 17:05:27] ====================
[2020-1-2 17:05:28] Error: The requested accessory 'NetworkDevice' was not registered by any plugin.
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by AlexGustafsson** [comment]
Try to run:

```
sudo apt-get remove nodejs
sudo apt-get remove npm
```

I usually follow this guide when installing Node on Ubuntu:
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04#installing-using-a-ppa

But you may have more luck using [NVM](https://github.com/nvm-sh/nvm).

**Comment by dcaccount** [comment]
I do not understand, when reinstalling nodejs I get following message:

> nodejs is already the newest version (8.17.0-1nodesource1).

but I keep getting the error (in Homebridge):

> /homebridge-wol requires Node version of >=11.0.0 which does not satisfy the current Node version of v8.17.0. 

Please help!

**Comment by AlexGustafsson** [comment]
You've found the source of the issue.

First, uninstall node:
```

**Comment by dcaccount** [comment]
Hello, first of all thanks for helping. Still no luck.

I have installed:

> daniele@raspberrypi:/usr/lib/node_modules $ nvm install stable
Downloading and installing node v13.5.0...
Local cache found: $NVM_DIR/.cache/bin/node-v13.5.0-linux-armv7l/node-v13.5.0-linux-armv7l.tar.xz
Checksums match! Using existing downloaded archive $NVM_DIR/.cache/bin/node-v13.5.0-linux-armv7l/node-v13.5.0-linux-armv7l.tar.xz
Now using node v13.5.0 (npm v6.13.4)

and then:

> nvm ls
         v4.9.1
        v6.17.1
        v8.17.0
       v10.18.0
       v12.14.0
->      v13.5.0
default -> node (-> v13.5.0)
node -> stable (-> v13.5.0) (default)
stable -> 13.5 (-> v13.5.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/erbium (-> v12.14.0)
lts/argon -> v4.9.1
lts/boron -> v6.17.1
lts/carbon -> v8.17.0
lts/dubnium -> v10.18.0
lts/erbium -> v12.14.0

but in "homebridge.err" I get following error:

> usr/bin/env: "node": File o directory not existing 

What can I do? Thanks!

**Comment by AlexGustafsson** [comment]
What tappens if you run `env node`? If nothing appears you haven’t installed nvm properly - you’ll have to make sure that you’re referencing the nvm script in your profile.

You can also try `nvm alias default node`

**Comment by dcaccount** [comment]
> What happens if you run `env node`? If nothing appears you haven’t installed nvm properly - you’ll have to make sure that you’re referencing the nvm script in your profile.
> 

I get:

> env: "node": No such a file or directory

**Comment by AlexGustafsson** [comment]
Make sure you follow the install instructions: https://github.com/nvm-sh/nvm/blob/master/README.md#installing-and-updating

Especially the part about adding to your profile. Restart your raspberry pi afterwards.

**Comment by dcaccount** [comment]
I have been able to install 11.15.0 and the issue has now changed.

Now the other packages installed require their "old" nodejs version and refuse to startup.

For instance:

> Error: The module '/usr/lib/node_modules/homebridge-gpio-device/node_modules/node-wiring-pi/build/Release/nodeWiringPi.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing

How can I address this issue?

Thanks!

**Comment by AlexGustafsson** [comment]
Great! Find the path where node modules are installed and nuke that directory.

On Unix systems they are normally placed in /usr/local/lib/node or /usr/local/lib/node_modules when installed globally.

You will have to reinstall packages after you’ve removed the directory. You can use npm list -g to first find any globally installed packages.

**Comment by produdegr** [comment]
@dcaccount  I had same issue of other modules relying on old 8.x.x node.
I rolled back to homebridge-wol V3.2.5
You can do that using:
npm install -g homebridge-wol@3.2.5
This solved it for me. I wish homebridge-wol V4.0.0 could be made to work with older node, but if security fixes are involved then it is wishful thinking.

**Comment by AlexGustafsson** [comment]
@produdegr The choice was made due to the lack of language features needlessly increasing the complexity and decreasing readability. The plugin has been rewritten to use async/await where it has previously been using plain promises.

Unfortunately I don’t have much time to spend on the plugin so when it finally came to improve it I decided to do so for the coming years.

Even though it is possible to install an older version of the plugin, I would recommend against it since there have been several noticeable fixes. I would accept a PR backporting the fixes to a previous version as a form of legacy branch if anyone has the time and interest in doing so.

I understand the new version comes at the cost of users having to upgrade where it is not always possible or easy. Unfortunately I will not be able to support old versions, but still feel free to open up issues about potential problems!

**Comment by produdegr** [comment]
Thanks, I appreciate this explanation.

**Comment by AlexGustafsson** [comment]
Closing as the main issue is solved. Feel free to continue the discussion here if you need more help, @dcaccount.

**Comment by AlexGustafsson** [comment]
Homebridge WoL 4.2.0 works with node 10 now. It's the oldest officially supported version. See: [https://nodejs.org/en/about/releases/](https://nodejs.org/en/about/releases/).
