### ISSUE TITLE
v4+ requires at least node 10 to run

### ISSUE THREAD

**Issue by bbaraniec** [AlexGustafsson/homebridge-wol#86]
npm WARN notsup Unsupported engine for homebridge-wol@4.0.0: wanted: {"node":">=11.0.0","homebridge":">=0.4.0"} (current: {"node":"8.17.0","npm":"6.13.4"})

**Comment by AlexGustafsson** [comment]
I've made some changes which now allows for node 10 to work as well. Node 10 is the latest long term support version which has entered the maintenance period. It's basically the oldest supported version.

**Comment by AlexGustafsson** [comment]
Closing this as Node 10 is the oldest supported version of Node and this plugin works fine with it. Please refer to: https://nodejs.org/en/about/releases/.
