### ISSUE TITLE
Docker homebridge ssh "shutdownCommand" doesn't appear to function correctly.

### ISSUE THREAD

**Issue by simonlock** [AlexGustafsson/homebridge-wol#88]
### Backstory
I've recently migrated my homebridge installation to now using docker which is running on a raspberry pi. I was previously running homebridge in a Freenas jail and using homebridge-wol but this was running as root; now docker homebridge is running as user "abc". On Freenas I could successfully both wake on lan and shutdown my win10 pc.

The homebridge-config-ui (v4.7.0) now has an option to enter the terminal of the running homebridge docker instance and from there I had the ability to generate new ssh keys for the user "abc". From this terminal, I can ssh into my win10 pc and also issue a command to shut down my windows pc over ssh. I generated my keys as per:

https://github.com/oznu/docker-homebridge/issues/113

i.e. ssh -i /homebridge/.ssh/id_rsa simon@simon-pc shutdown /s /f /t 0

the above command successfully shuts down my win10 pc from the terminal. 

### Issue
However, issuing the very same command using the homebridge-wol config now fails:

i.e. "shutdownCommand": "ssh -i /homebridge/.ssh/id_rsa simon@simon-pc shutdown /s /f /t 0"

### Environment
* os & os version: Raspberry PI docker  image.
* node version: v12.14.1
* homebridge version: Version 0.4.50
* homebridge-wol version: v4.1.2
* homebridge-config-ui (v4.7.0) 
### Configuration
My configuration looks like this:
```
  {
            "accessory": "NetworkDevice",
            "name": "simon-pc",
            "mac": "XX-XX-XX-XX-XX-XX",
            "broadcastAddress": "172.16.28.254",
            "wakeGraceTime": 0,
            "shutdownGraceTime": 0,
            "ip": "172.16.28.6",
            "shutdownCommand": "ssh -i /homebridge/.ssh/id_rsa simon@simon-pc shutdown /s /f /t 0"
        }

### Log

[1/12/2020, 2:57:20 PM] [simon-pc] An error occured while trying to shut down "simon-pc" (172.16.28.6): Error: Command failed: ssh -i /homebridge/.ssh/id_rsa simon@simon-pc shutdown /s /f /t 0
Host key verification failed.

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: 'ssh -i /homebridge/.ssh/id_rsa simon@simon-pc shutdown /s /f /t 0',
  stdout: '',
  stderr: 'Host key verification failed.\r\n'
}

The wake up (wol) components continue to function correctly.

**Comment by AlexGustafsson** [comment]
See #82.

That host key verification fails means that the user running Homebridge does not trust your remote PC. If you run Homebridge as another user than you're using when testing to SSH into the machine, this can easily be fixed.

When you first connect to a machine you usually get a prompt like this:

```
RSA key fingerprint is 96:a9:23:5c:cc:d1:0a:d4:70:22:93:e9:9e:1e:74:2f.
Are you sure you want to continue connecting (yes/no)? yes
```

Accepting it will add it to the file ~/.ssh/known_hosts and thus verify the host. If the host is not trusted, you get an error message.

You can try the following to connect to the server once as the user running Homebridge to ensure that the PC is marked as trusted:

```
sudo -u homebridge-user ssh <user>@<mac ip>
```

If you are running Homebridge as another user, you will also have to setup SSH keys for that user.

**Comment by simonlock** [comment]
Thank you very much Alex as you suggested using: "sudo -u homebridge-user ssh <user>@<hostname> did the trick.

The docker version of Homebridge appears to run as user "abc" but the terminal runs as "root".

"shutdownCommand": "ssh -i /homebridge/.ssh/id_rsa simon@simon-pc shutdown /s /f /t 0"

now works perfectly.

**Comment by AlexGustafsson** [comment]
Great!

**Comment by Hallo-457** [comment]
Hi simonlock,

how did you configured your homebridge-wol plugin on the FreeNAS? Im trying it now for several months and i cant get it to work.

**Comment by simonlock** [comment]
Hi @Hallo-457

Sorry since this post I've moved to using Homeassistant. I'm only using Homebridge for a Nest Thermostat now.
As I recall my issue was not realising that Homebridge in Docker was running as user abc and not root.
