### ISSUE TITLE
Can't get 4.2.0 to work

### ISSUE THREAD

**Issue by mignz** [AlexGustafsson/homebridge-wol#94]
So I upgraded from 3.2.5 to 4.2.0 and nothing works anymore. The wol device status can't be fetched, it doesn't start or stop the device.

Nothing on the logs... they are enabled in the config.

If you want to replicate, you can have my setup exactly: `oznu/homebridge:2.0.0-no-avahi` **docker** image with the following env vars:

- DSM_HOSTNAME=NAS
- HOMEBRIDGE_CONFIG_UI=1
- HOMEBRIDGE_CONFIG_UI_PORT=8080
- TZ=Europe/Lisbon

And then I followed [this](https://github.com/oznu/docker-homebridge/issues/126) guide to upgrade NodeJS to a version above 12.0.0 which your plugin requires. I'm using NodeJS 12.16.1. I also updated Homebridge to version 0.4.52 from the Homebridge UI.

Finally, the config:

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "...",
        "port": 51826,
        "pin": "xxx-xx-xxx"
    },
    "description": "",
    "accessories": [
        {
            "accessory": "NetworkDevice",
            "name": "My PC",
            "mac": "...",
            "ip": "10.0.0.10",
            "broadcastAddress": "10.0.0.255",
            "pingInterval": 5,
            "pingCommand": "curl -m 2 -s http://10.0.0.10:5001",
            "timeout": 2,
            "shutdownCommand": "curl -m 2 -s http://10.0.0.10:5001/.../suspend",
            "shutdownGraceTime": 5,
            "log": true,
            "logPinger": true
        }
    ],
    "platforms": [
        {
            "name": "HomebridgeUI",
            "port": 8080,
            "auth": "form",
            "theme": "red",
            "tempUnits": "c",
            "platform": "config"
        },
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Q90R TV",
                    "ip": "10.0.0.4",
                    "mac": "..."
                }
            ]
        }
    ]
}
```

Reverted to 3.2.5 and everything's fine again.

**Comment by AlexGustafsson** [comment]
Hi! If you get the time and are willing to try again, could you try to add `debugLog: true` to your accessory config?

**Comment by AlexGustafsson** [comment]
Were you able to resolve this?

**Comment by mignz** [comment]
No I did not, I'm still using 3.2.5. I'm unable to try your inputs, however. Haven't been home for a while and won't be until the end of july. I'll try it out then. And sorry for the three month delay 😄

**Comment by AlexGustafsson** [comment]
No worries about the delay, take your time! I’ll keep this issue open until we’re able to sort things out.

**Comment by AlexGustafsson** [comment]
This project is being rewritten in an upcoming version. I'm closing this since it is now rather stale. Please feel free to give v4 another try or v5 when it comes around. Don't hesitate to reopen this issue or open a new one if troubles come your way.

See #124 for more information.
