### ISSUE TITLE
Can’t turn on PC

### ISSUE THREAD

**Issue by npburns224** [AlexGustafsson/homebridge-wol#99]
I don’t have any issues turning off my PC, but I’m unable to turn it back on. The switch flips itself off once the wakeGraceTime has passed.

**Comment by Ufocultist** [comment]
Hello.
Do you have "broadcastAddress": "192.168.1.254", in your conf?

**Comment by npburns224** [comment]
Here is my current config:

**Comment by npburns224** [comment]
Here is my current config:
```
{
        "accessory": "NetworkDevice",
        "name": "PC",
        "mac": "--ADDRESS--",
        "ip": "10.1.44.20",
        "shutdownCommand": "curl http://10.1.44.20:5001/secret/shutdown",
        "pingsToChange": 3,
        "wakeGraceTime": 25,
        "shutdownGraceTime": 15
}
```

I also tried adding the line ` "broadcastAddress": "10.1.44.20"`, but still had no luck.

**Comment by Ufocultist** [comment]
Hello, try this "broadcastAddress": "10.1.44.255"

**Comment by mafyata** [comment]
I solved my problem when I disabled fast boot in power options in windows.

**Comment by AlexGustafsson** [comment]
Were you able to solve this issue? If it’s a Windows PC, it’s usually a BIOS setting and/or fast boot stopping you.

**Comment by npburns224** [comment]
I've made sure to enable WoL in my BIOS, disable fast startup in the Windows power settings, and connect to the network via Ethernet, but I'm still not having much luck unfortunately. 
I'm using the solution from #93 to shut down my PC which seems to work flawlessly, however I've yet to be successful in starting the machine back up.

I'm sometimes able to wake the machine from a hibernation state, but I've yet to be able to wake it from a shutdown state.
I'm not too sure what else I should look into at this point after poking around for a while.

**Comment by AlexGustafsson** [comment]
I share your frustration when it comes to WoL, it seems to work well sometimes on some machines, but never on others. Unfortunately I don’t think there’s much I can do to help.

If you’re sure that it has woken up your PC from hibernation, then there’s no real software error related to this package or any network issue related to your setup. 

Try to read up on Wake On LAN on your motherboard, update BIOS etc. Please share if you find a solution!

**Comment by AlexGustafsson** [comment]
Closing as there’s not much to be done from the plugin’s point of view. Please share your solution if you find any and feel free to reopen if you think this is an issue with the plugin itself.
